import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '@/Components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200 h-screen flex gap-3">
        <Sidebar/>
        {children}
      </body>
    </html>
  )
}
