import { Inter } from 'next/font/google';
import '../globals.css';
import Sidebar from '@/Components/Sidebar';
import Skill from '@/Components/Hooks/Global/jobs';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200 h-screen lg:flex`}>
        {/* Sidebar */}


        {/* Main Content */}
        <div className="lg:ml-[18rem] w-full p-4 overflow-y-auto">
          <Skill>
            <Sidebar className="fixed top-0 left-0 lg:w-[18rem] h-screen bg-slate-50 p-2 overflow-y-auto" />
            {children}
          </Skill>
        </div>
      </body>
    </html>
  );
}
